# Generated by Django 4.1.4 on 2024-03-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_remove_product_product_id_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=250, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
